# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maven dependency updates in pom.xml
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      
  # Docker updates in docker-compose.yml and Dockerfiles
  - package-ecosystem: "docker"
    directory: "/src/main/docker/"
    schedule:
      interval: "weekly"

  # Workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
