apiVersion: apps/v1
kind: Deployment
metadata:
  name: proficient-pixy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
      annotations:
        proxy.istio.io/config: |
          {
            "holdApplicationUntilProxyStarts": true
          }
    spec:
      restartPolicy: Always
      containers:
        - name: app
          image: ghcr.io/jumpingelephant/proficient-pixy
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: proficient-pixy-config
          startupProbe: # checks if the application has finished its startup process
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe: # checks if the application is running
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe: # checks if the application is ready to handle requests
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            failureThreshold: 2
      terminationGracePeriodSeconds: 10
