apiVersion: v1
kind: Service
metadata:
  name: proficient-pixy
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: web
