apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pixy-greeting-handshake-spc
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    roleName: "spc-read"
    objects: |
      - objectName: greeting.handshake
        secretPath: "/v1/sample-app/data/proficient-pixy/greeting/handshake"
        secretKey: "type"
      - objectName: greeting.handshake.privateKey
        secretPath: "/v1/sample-app/data/proficient-pixy/greeting/handshake"
        secretKey: "privateKey"